name: RottenFleshToLeather
version: '${project.version}'
main: net.aniby.rottenfleshtoleather.RottenFleshToLeather
api-version: '1.20'
load: STARTUP
authors: [An1by]
description: This plugin allows smelting rotten flesh into leather
website: https://aniby.net/